// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GRPCReq struct {
	ReqSeq               string   `protobuf:"bytes,1,opt,name=reqSeq,proto3" json:"reqSeq,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GRPCReq) Reset()         { *m = GRPCReq{} }
func (m *GRPCReq) String() string { return proto.CompactTextString(m) }
func (*GRPCReq) ProtoMessage()    {}
func (*GRPCReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_b9de62e9c22ef904, []int{0}
}
func (m *GRPCReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GRPCReq.Unmarshal(m, b)
}
func (m *GRPCReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GRPCReq.Marshal(b, m, deterministic)
}
func (dst *GRPCReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GRPCReq.Merge(dst, src)
}
func (m *GRPCReq) XXX_Size() int {
	return xxx_messageInfo_GRPCReq.Size(m)
}
func (m *GRPCReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GRPCReq.DiscardUnknown(m)
}

var xxx_messageInfo_GRPCReq proto.InternalMessageInfo

func (m *GRPCReq) GetReqSeq() string {
	if m != nil {
		return m.ReqSeq
	}
	return ""
}

func (m *GRPCReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GRPCResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Result               string   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GRPCResp) Reset()         { *m = GRPCResp{} }
func (m *GRPCResp) String() string { return proto.CompactTextString(m) }
func (*GRPCResp) ProtoMessage()    {}
func (*GRPCResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_b9de62e9c22ef904, []int{1}
}
func (m *GRPCResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GRPCResp.Unmarshal(m, b)
}
func (m *GRPCResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GRPCResp.Marshal(b, m, deterministic)
}
func (dst *GRPCResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GRPCResp.Merge(dst, src)
}
func (m *GRPCResp) XXX_Size() int {
	return xxx_messageInfo_GRPCResp.Size(m)
}
func (m *GRPCResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GRPCResp.DiscardUnknown(m)
}

var xxx_messageInfo_GRPCResp proto.InternalMessageInfo

func (m *GRPCResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GRPCResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GRPCResp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*GRPCReq)(nil), "proto.gRPCReq")
	proto.RegisterType((*GRPCResp)(nil), "proto.gRPCResp")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_grpc_b9de62e9c22ef904) }

var fileDescriptor_grpc_b9de62e9c22ef904 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2f, 0x2a, 0x48,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xa6, 0x5c, 0xec, 0xe9, 0x41,
	0x01, 0xce, 0x41, 0xa9, 0x85, 0x42, 0x62, 0x5c, 0x6c, 0x45, 0xa9, 0x85, 0xc1, 0xa9, 0x85, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa,
	0x04, 0x13, 0x58, 0x14, 0xcc, 0x56, 0xf2, 0xe0, 0xe2, 0x80, 0x68, 0x2b, 0x2e, 0x00, 0xc9, 0x27,
	0xe7, 0xa7, 0xa4, 0x82, 0x75, 0xb1, 0x06, 0x81, 0xd9, 0x42, 0x02, 0x5c, 0xcc, 0xb9, 0xc5, 0xe9,
	0x50, 0x2d, 0x20, 0x26, 0xc4, 0xf4, 0xe2, 0xd2, 0x9c, 0x12, 0x09, 0x66, 0x98, 0xe9, 0x20, 0x9e,
	0x91, 0x29, 0x17, 0x8b, 0x7b, 0x50, 0x80, 0xb3, 0x90, 0x2e, 0x17, 0x87, 0x73, 0x62, 0x4e, 0x0e,
	0x98, 0xcd, 0x07, 0x71, 0xa3, 0x1e, 0xd4, 0x65, 0x52, 0xfc, 0x28, 0xfc, 0xe2, 0x02, 0x25, 0x86,
	0x24, 0x36, 0xb0, 0x88, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x30, 0xd6, 0x96, 0xa5, 0xd3, 0x00,
	0x00, 0x00,
}
